server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/booking_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password={cipher}b1be3964bb72d623f5092d4ef0f8a49cf71dec0bccb4cd964a99ec75f8ffb8f8
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

flight.service.url=http://flight-service
auth.service.url=http://localhost:8081

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

logging.level.com.flightapp.booking=INFO
logging.level.org.hibernate.SQL=WARN
