server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/booking_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password="{cipher}fa49f973c332fddc1d81a24d212209bf2457e122bf2f598c8ac194fedf014f91"
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

flight.service.url=http://localhost:8082

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

logging.level.com.flightapp.booking=INFO
logging.level.org.hibernate.SQL=WARN
